docs(mtls): add example in combination with 'KafkaTopic' and 'KafkaUser'
strimzi/strimzi-canary pull request #231
Opened 2024-04-30 12:59 UTC by sebastiangaiser

closes #230

2024-04-30 13:52 UTC, ppatierno requested changes

2024-04-30 14:06 UTC, ppatierno requested changes

2024-04-30 14:06 UTC, ppatierno commented on packaging/examples/mtls/mtls.yaml
> +        image: quay.io/strimzi/canary:0.6.0
under packaging folder tag should be latest
```suggestion
        image: quay.io/strimzi/canary:latest
```

2024-04-30 14:09 UTC, ppatierno approved these changes
LGTM. Thanks!

2024-04-30 15:59 UTC, scholzj reviewed
* Maybe we should add some README.md into the folder with some explanation?
* Maybe we should make it in the path a bit more clear that this is about linking it with Strimzi-based Kafka cluster and not as muhc about mTLS as the path suggests? E.g. `packaging/examples/strimzi-tls-auth`?
* It seems disconnected from the release tooling. So if we ever do another release of this, nothing will hapen with this. So I guess the `MAkefile` tasks should be updated to:
    * Include this in the release package
    * Copy it to `/examples`
    * Make sure the Deployment YAML is up to date (I think having a separate deployment is a bit controversial as it would get easily out of date. But not sure how to do it better other thn having just a README.md with YAML snippets.)
    * Update the Deployment YAML during release with the release version (to use the correct container)

I guess having this just as a section in the main README.md would safe a lot of these things. But I'm fine if we want to have it in examples. We just have to make sure it is done properly or it will be obsolete and forgotten soon.

2024-05-02 10:19 UTC, sebastiangaiser commented
If you want I can move the files to a different path, split them up, ... Please tell me where :D

The structure of the readme and the makefile parts are not on me, I guess. So maybe this should be in another PR.

2024-05-02 13:28 UTC, scholzj commented
> If you want I can move the files to a different path, split them up, ... Please tell me where :D
> 
> The structure of the readme and the makefile parts are not on me, I guess. So maybe this should be in another PR.

I think there are several problems with this:
* You do not really have an example. You have installation files. 
    * Installation files need to be properly maintained (e.g. if you add a new environment variable you have to add it to all instances).
    * Installation files need to be package as part of the release
    * Installation files need to be updated as part of the release (if nothing else, the image tag changes)

If we merge it as it is, it will never be part of any release, most people will never find it and it will eventually get outdated until it is one day deleted. That is what I'm afraid of.

2024-05-11 12:16 UTC, sebastiangaiser commented
Would the releasing be easier with a Helm chart? I think this would not be that kind of documentation but in case when you run `helm template...` you would also get the "raw" manifests, too.

2024-05-12 00:26 UTC, scholzj commented
> Would the releasing be easier with a Helm chart? I think this would not be that kind of documentation but in case when you run helm template... you would also get the "raw" manifests, too.

Well, yes and not I guess. We would still need to integrate it into the tooling and CIs.

2024-11-29 00:08 UTC, closed without merging